# Generated by Django 5.0.3 on 2024-04-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewInsight',
            fields=[
                ('platform_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=30)),
                ('no_of_page_reach', models.IntegerField(default=0)),
                ('no_of_page_likes', models.IntegerField(default=0)),
                ('no_of_page_followers', models.IntegerField(default=0)),
                ('no_of_published_post', models.IntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=30)),
                ('post_content', models.TextField()),
                ('no_of_likes', models.IntegerField(default=0)),
                ('no_of_comments', models.IntegerField(default=0)),
                ('no_of_shares', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UploadImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
